namespace _01.ReactWebApiDemo.Server.Models;

/// <summary>
/// Represents the backend response shown after the learner submits the form.
/// </summary>
public class PracticeMessageResponse
{
    /// <summary>
    /// Gets or sets the heading shown to the learner.
    /// </summary>
    public string Heading { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the main coaching message generated by the backend.
    /// </summary>
    public string Message { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the next small action the learner should take.
    /// </summary>
    public string NextStep { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets reminder items rendered as a short checklist in React.
    /// </summary>
    public List<string> ReminderItems { get; set; } = [];
}
