services:
  postgres:
    image: postgres:16-alpine
    container_name: itec323_comprehensive_app_postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT:-5434}:5432"
    volumes:
      - comprehensive_postgres_data:/var/lib/postgresql/data

volumes:
  comprehensive_postgres_data:
