namespace GeminiTextAndRagApiDemo.Models;

/// <summary>
/// Represents the API response for a RAG question.
/// </summary>
public class RagQuestionResponse
{
    /// <summary>
    /// Gets or sets the original question.
    /// </summary>
    public required string Question { get; set; }

    /// <summary>
    /// Gets or sets the answer generated by Gemini.
    /// </summary>
    public required string Answer { get; set; }

    /// <summary>
    /// Gets or sets the source documents used to ground the answer.
    /// </summary>
    public required List<RagSourceItem> Sources { get; set; }
}
