services:
  postgres:
    image: postgres:16-alpine
    container_name: itec323_postgres_docker
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres_docker_db
      POSTGRES_USER: postgres_docker_user
      POSTGRES_PASSWORD: postgres_docker_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
