services:
  tensorflow-mnist-app:
    build: .
    image: tensorflow-mnist-app:latest
    container_name: tensorflow-mnist-classification
    # Uncomment the following lines if you want to mount volumes for development
    # volumes:
    #   - .:/src
    #   - ./models:/src/models
    # environment:
    #   - PYTHONUNBUFFERED=1
    # command: ["python", "-u", "tensorflow_mnist.py"]
    
  # Optional: Add a development service with interactive shell
  tensorflow-mnist-dev:
    build: .
    image: tensorflow-mnist-app:latest
    container_name: tensorflow-mnist-classification-dev
    volumes:
      - .:/src
    working_dir: /src
    stdin_open: true
    tty: true
    command: ["/bin/bash"]
    profiles:
      - dev
