// <auto-generated />
using System;
using ComprehensiveApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ComprehensiveApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ComprehensiveApp.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Hardware"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Office"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Accessories"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Networking"
                        });
                });

            modelBuilder.Entity("ComprehensiveApp.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Brisbane",
                            CreatedAtUtc = new DateTime(2026, 1, 15, 8, 30, 0, 0, DateTimeKind.Utc),
                            Email = "alex.johnson@example.com",
                            FullName = "Alex Johnson"
                        },
                        new
                        {
                            Id = 2,
                            City = "Sydney",
                            CreatedAtUtc = new DateTime(2026, 2, 10, 13, 45, 0, 0, DateTimeKind.Utc),
                            Email = "morgan.lee@example.com",
                            FullName = "Morgan Lee"
                        },
                        new
                        {
                            Id = 3,
                            City = "Melbourne",
                            CreatedAtUtc = new DateTime(2026, 3, 1, 10, 15, 0, 0, DateTimeKind.Utc),
                            Email = "taylor.chen@example.com",
                            FullName = "Taylor Chen"
                        });
                });

            modelBuilder.Entity("ComprehensiveApp.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("OrderDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerId = 1,
                            Notes = "Deliver to front desk.",
                            OrderDateUtc = new DateTime(2026, 2, 10, 13, 45, 0, 0, DateTimeKind.Utc),
                            Status = "Paid"
                        },
                        new
                        {
                            Id = 2,
                            CustomerId = 2,
                            Notes = "Bundle items into one shipment.",
                            OrderDateUtc = new DateTime(2026, 3, 1, 10, 15, 0, 0, DateTimeKind.Utc),
                            Status = "Pending"
                        });
                });

            modelBuilder.Entity("ComprehensiveApp.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrderId = 1,
                            ProductId = 1,
                            Quantity = 1,
                            UnitPrice = 149.00m
                        },
                        new
                        {
                            Id = 2,
                            OrderId = 1,
                            ProductId = 6,
                            Quantity = 3,
                            UnitPrice = 24.50m
                        },
                        new
                        {
                            Id = 3,
                            OrderId = 2,
                            ProductId = 2,
                            Quantity = 1,
                            UnitPrice = 219.00m
                        });
                });

            modelBuilder.Entity("ComprehensiveApp.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 3,
                            CreatedAtUtc = new DateTime(2026, 1, 15, 8, 30, 0, 0, DateTimeKind.Utc),
                            Description = "Hot-swappable keyboard for developers.",
                            Name = "Mechanical Keyboard",
                            Price = 149.00m,
                            StockQuantity = 18
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedAtUtc = new DateTime(2026, 1, 17, 8, 30, 0, 0, DateTimeKind.Utc),
                            Description = "Docking station with dual display outputs.",
                            Name = "USB-C Dock",
                            Price = 219.00m,
                            StockQuantity = 9
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            CreatedAtUtc = new DateTime(2026, 2, 10, 13, 45, 0, 0, DateTimeKind.Utc),
                            Description = "Comfortable office chair for long work sessions.",
                            Name = "Ergonomic Chair",
                            Price = 399.00m,
                            StockQuantity = 5
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            CreatedAtUtc = new DateTime(2026, 2, 11, 13, 45, 0, 0, DateTimeKind.Utc),
                            Description = "Small-office router with VLAN support.",
                            Name = "Wi-Fi 6 Router",
                            Price = 279.00m,
                            StockQuantity = 7
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            CreatedAtUtc = new DateTime(2026, 3, 1, 10, 15, 0, 0, DateTimeKind.Utc),
                            Description = "27-inch display for design and analytics.",
                            Name = "4K Monitor",
                            Price = 499.00m,
                            StockQuantity = 6
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            CreatedAtUtc = new DateTime(2026, 3, 2, 10, 15, 0, 0, DateTimeKind.Utc),
                            Description = "Pack of premium notebooks for workshops.",
                            Name = "Notebook Set",
                            Price = 24.50m,
                            StockQuantity = 42
                        });
                });

            modelBuilder.Entity("ComprehensiveApp.Models.Order", b =>
                {
                    b.HasOne("ComprehensiveApp.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ComprehensiveApp.Models.OrderItem", b =>
                {
                    b.HasOne("ComprehensiveApp.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComprehensiveApp.Models.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ComprehensiveApp.Models.Product", b =>
                {
                    b.HasOne("ComprehensiveApp.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ComprehensiveApp.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ComprehensiveApp.Models.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("ComprehensiveApp.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("ComprehensiveApp.Models.Product", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
