using ConcurrencyConflicts.Data;
using ConcurrencyConflicts.Models;
using Microsoft.EntityFrameworkCore;

namespace ConcurrencyConflicts.Services;

/// <summary>
/// Provides query inspection and mapping helpers for the concurrency demo.
/// </summary>
public class ConcurrencyConflictDemoService
{
    private readonly AppDbContext _context;

    /// <summary>
    /// Initializes a new instance of the <see cref="ConcurrencyConflictDemoService"/> class.
    /// </summary>
    /// <param name="context">The application database context.</param>
    public ConcurrencyConflictDemoService(AppDbContext context)
    {
        _context = context;
    }

    /// <summary>
    /// Gets the SQL used to load products for editing.
    /// </summary>
    /// <returns>The SQL text generated by EF Core.</returns>
    public string GetEditableProductsSql()
    {
        return _context.Products
            .AsNoTracking()
            .OrderBy(product => product.Name)
            .ToQueryString();
    }

    /// <summary>
    /// Gets an example update statement showing how the version check works.
    /// </summary>
    /// <returns>A sample SQL statement.</returns>
    public string GetSampleUpdateSql()
    {
        return """
UPDATE "Products"
SET "Name" = @p0,
    "Notes" = @p1,
    "Price" = @p2,
    "QuantityInStock" = @p3,
    "Version" = @p4,
    "LastModifiedUtc" = @p5
WHERE "Id" = @p6 AND "Version" = @p7;
""";
    }

    /// <summary>
    /// Maps a <see cref="Product"/> entity to the form model.
    /// </summary>
    /// <param name="product">The source product.</param>
    /// <returns>The mapped form model.</returns>
    public static ProductInputModel ToInputModel(Product product)
    {
        return new ProductInputModel
        {
            Id = product.Id,
            Name = product.Name,
            Price = product.Price,
            QuantityInStock = product.QuantityInStock,
            Notes = product.Notes,
            Version = product.Version,
            DatabaseVersion = product.Version
        };
    }
}
